name: www.timothyjohnson.com
favicon: null
layout_spectrum: 0.00068
typography_spectrum: 0.25292
title: timothyjohnson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8ebceb'
    - '#a69b90'
    - '#6d6257'
    - '#33391d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
