name: www.timothyjohnson.com
favicon: null
layout_spectrum: 0.00417
typography_spectrum: 0.25292
title: timothyjohnson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8f6943'
    - '#5e3215'
    - '#999068'
    - '#bcaba2'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
