name: www.timothyjohnson.com
favicon: null
layout_spectrum: 0.00083
typography_spectrum: 0.25292
title: timothyjohnson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#67756b'
    - '#425051'
    - '#000000'
    - '#8d8973'
    - '#bdb08b'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
