name: www.timothyjohnson.com
favicon: null
layout_spectrum: 0.2812509306240827
typography_spectrum: 0.06871803849935532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130c11'
    - '#7d0013'
    - '#8a5799'
    - '#c89c80'
    - '#fffdfe'
  brandStrength: 0.5
  lightness: 0.8702172450721264
  saturation: 0.12722213426604867
  rhythmicContrast: 0.7515400156844407
purpose: []
